darwin-module: stop setting unused comma.package option
Otherwise evaluation fails:

```
error: The option `programs.nix-index-database.comma.package' does not exist. Definition values:
- In `/nix/store/ajkx81c4pl0dyqzja38mgj41mp0r44il-source/darwin-module.nix':
    {
      _type = "override";
      content = <derivation nix-index-with-db-0.1.8>;
      priority = 1000;
    }
```